query {
  projects {
    data {
      id
      attributes {
        title
        subtitle
        description
        external_url
        cover {
          data {
            id
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
