query fetchProjects($category: String!) {
  projects(filters: { Category: { eq: $category } }, sort: "publishedAt:DESC") {
    data {
      id
      attributes {
        title
        Category
        subtitle
        description
        external_url
        cover {
          data {
            id
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
